# Generated by Django 4.2.2 on 2023-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=42)),
                ('lastname', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=12)),
                ('phonenumber', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
    ]
