# Generated by Django 4.2.2 on 2023-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('customer_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
