# Generated by Django 4.2.3 on 2023-08-20 16:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Product_cart'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='customer_ID',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='list_of_items',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity_of_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 16, 6, 27, 129262, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(default=datetime.datetime(2023, 8, 20, 16, 12, 37, 828125, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
