# Generated by Django 4.2.3 on 2023-07-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('cart', '0001_initial'),
        ('delivery', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('shipments', models.ManyToManyField(to='delivery.delivery')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
